pipeline {
  agent {
    label 'docker-node'  // Use an agent label that corresponds to your Docker-capable node
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}
